
![Data Processing Funnel](d_1.png)

**Purpose:** This notebook focuses on loading the necessary data files for the coral reef analysis project and performing initial data cleaning and preprocessing steps. These steps aim to prepare the data for subsequent analyses in other notebooks.

**Inputs:**

* `CREMP_Pcover_2023_StonyCoralSpecies.csv` 
* `CREMP_Pcover_2023_TaxaGroups.csv` 
* `CREMP_Temperatures_2023.csv` 
* `CREMP_Stations_2023.csv`

**Outputs:**

* Cleaned and preprocessed DataFrames: `df_stony_coral`, `df_taxa_groups`, `df_temperature`, `df_locations`.


**Preprocessing Steps:**

1.  **Load Data:** Load the data files into Pandas DataFrames.
2.  **Inspect Data:** Display the first few rows and column information of each DataFrame to understand its structure and data types.
3.  **Handle Missing Values:** Identify and address missing values appropriately (e.g., drop rows/columns, fill with a value).
4.  **Standardize Column Names:** Ensure consistency in column names across DataFrames.
5.  **Extract Year:** Extract the year from any date or datetime columns in the temperature data.
6.  **Merge Location Data (Optional):** If needed, merge location data with percent cover data for spatial analysis.
7.  **Save Processed Data (Optional):** Save the cleaned and preprocessed DataFrames for use in other notebooks.

**Notes:**

* This notebook assumes the data files are located in a subdirectory named "C:\\Users\\vijai\\Desktop\Florida". Adjust the file paths as necessary.
* The specific preprocessing steps may vary depending on the format and content of the original data files.

In [1]:
import pandas as pd

import os

# Define data directory (adjust if necessary)
data_dir = "C:\\Users\\vijai\\Desktop\Florida"

# Define file paths
stony_coral_file = os.path.join(data_dir, "CREMP_Pcover_2023_StonyCoralSpecies.csv")  # Replace with actual file name/extension
taxa_groups_file = os.path.join(data_dir, "CREMP_Pcover_2023_TaxaGroups.csv")  # Replace with actual file name/extension
temperature_file = os.path.join(data_dir, "CREMP_Temperatures_2023.csv")  # Replace with actual file name/extension
locations_file = os.path.join(data_dir, "CREMP_Stations_2023.csv")  # Replace with actual file name/extension

![Data Processing Funnel](d_2.png)
#
## Defines the paths to the data files.  It's crucial to adjust the file paths to match the actual
## location and names of your data files.

In [2]:
# Load data
try:
    df_stony_coral = pd.read_csv(stony_coral_file)
    df_taxa_groups = pd.read_csv(taxa_groups_file)
    df_temperature = pd.read_csv(temperature_file)
    df_locations = pd.read_csv(locations_file)  # Changed to pd.read_csv
    print("Data files loaded successfully!")

except FileNotFoundError as e:
    print(f"Error: One or more data files not found: {e}")
except Exception as e:
    print(f"An error occurred while loading data: {e}")

Data files loaded successfully!

![Data Processing Funnel](d_3.png)
## This block inspects the loaded DataFrames by printing the first few rows
## (using df.head()) and displaying column information, data types, and
## non-null counts (using df.info()). This helps to understand the structure
## of the data.

In [3]:
# Inspect data
print("\n--- Stony Coral Data ---")
print(df_stony_coral.head())
print(df_stony_coral.info())

print("\n--- Taxa Groups Data ---")
print(df_taxa_groups.head())
print(df_taxa_groups.info())

print("\n--- Temperature Data ---")
print(df_temperature.head())
print(df_temperature.info())

print("\n--- Locations Data ---")
print(df_locations.head())
print(df_locations.info())

--- Stony Coral Data ---
   OID_  Year               Date Subregion Habitat  SiteID    Site_name  \
0     1  1996  7/25/1996 0:00:00        UK      HB      10  Rattlesnake
1     2  1996  7/25/1996 0:00:00        UK      HB      10  Rattlesnake
2     3  1996  7/25/1996 0:00:00        UK      HB      10  Rattlesnake
3     4  1996  7/25/1996 0:00:00        UK      HB      10  Rattlesnake
4     5  1996  7/22/1996 0:00:00        UK      HB      11   El Radabob

   StationID Surveyed_all_years  points  ...  Porites_porites_complex  \
0        101                  N     479  ...                      0.0
1        102                  N     525  ...                      0.0
2        103                  N     558  ...                      0.0
3        104                  N     446  ...                      0.0
4        111                  N     450  ...                      0.0

   Pseudodiploria_clivosa  Pseudodiploria_strigosa  Scleractinia  Scolymia_sp  \
0                     0.0                      0.0           0.0          0.0
1                     0.0                      0.0           0.0          0.0
2                     0.0                      0.0           0.0          0.0
3                     0.0                      0.0           0.0          0.0
4                     0.0                      0.0           0.0          0.0

   Siderastrea_radians  Siderastrea_siderea  Solenastrea_bournoni  \
0                  0.0                  0.0                   0.0
1                  0.0                  0.0                   0.0
2                  0.0                  0.0                   0.0
3                  0.0                  0.0                   0.0
4                  0.0                  0.0                   0.0

   Stephanocoenia_intersepta  Undaria_agaricites_complex
0                        0.0                         0.0
1                        0.0                         0.0
2                        0.0                         0.0
3                        0.0                         0.0
4                        0.0                         0.0

[5 rows x 50 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3918 entries, 0 to 3917
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   OID_                               3918 non-null   int64
 1   Year                               3918 non-null   int64
 2   Date                               3912 non-null   object
 3   Subregion                          3918 non-null   object
 4   Habitat                            3918 non-null   object
 5   SiteID                             3918 non-null   int64
 6   Site_name                          3918 non-null   object
 7   StationID                          3918 non-null   int64
 8   Surveyed_all_years                 3918 non-null   object
 9   points                             3918 non-null   int64
 10  Acropora_cervicornis               3918 non-null   float64
 11  Acropora_palmata                   3918 non-null   float64
 12  Agaricia_fragilis                  3918 non-null   float64
 13  Agaricia_lamarcki                  3918 non-null   float64
 14  Cladocora_arbuscula                3918 non-null   float64
 15  Colpophyllia_natans                3918 non-null   float64
 16  Dendrogyra_cylindrus               3918 non-null   float64
 17  Dichocoenia_stokesii               3918 non-null   float64
 18  Diploria_labyrinthiformis          3918 non-null   float64
 19  Eusmilia_fastigiata                3918 non-null   float64
 20  Favia_fragum                       3918 non-null   float64
 21  Helioseris_cucullata               3918 non-null   float64
 22  Isophyllia_rigida                  3918 non-null   float64
 23  Isophyllia_sinuosa                 3918 non-null   float64
 24  Madracis_aurentenra                3918 non-null   float64
 25  Madracis_decactis_complex          3918 non-null   float64
 26  Manicina_areolata                  3918 non-null   float64
 27  Meandrina_meandrites               3918 non-null   float64
 28  Millepora_alcicornis               3918 non-null   float64
 29  Millepora_complanata               3918 non-null   float64
 30  Montastraea_cavernosa              3918 non-null   float64
 31  Mussa_angulosa                     3918 non-null   float64
 32  Mycetophyllia_aliciae              3918 non-null   float64
 33  Mycetophyllia_ferox                3918 non-null   float64
 34  Mycetophyllia_lamarckiana_complex  3918 non-null   float64
 35  Oculina_diffusa                    3918 non-null   float64
 36  Oculina_robusta                    3918 non-null   float64
 37  Orbicella_annularis_complex        3918 non-null   float64
 38  Phyllangia_americana               3918 non-null   float64
 39  Porites_astreoides                 3918 non-null   float64
 40  Porites_porites_complex            3918 non-null   float64
 41  Pseudodiploria_clivosa             3918 non-null   float64
 42  Pseudodiploria_strigosa            3918 non-null   float64
 43  Scleractinia                       3918 non-null   float64
 44  Scolymia_sp                        3918 non-null   float64
 45  Siderastrea_radians                3918 non-null   float64
 46  Siderastrea_siderea                3918 non-null   float64
 47  Solenastrea_bournoni               3918 non-null   float64
 48  Stephanocoenia_intersepta          3918 non-null   float64
 49  Undaria_agaricites_complex         3918 non-null   float64
dtypes: float64(40), int64(5), object(5)
memory usage: 1.5+ MB
None

--- Taxa Groups Data ---
   Year       Date Subregion Habitat  SiteID    Site_name  StationID  \
0  1996  7/25/1996        UK      HB      10  Rattlesnake        101
1  1996  7/25/1996        UK      HB      10  Rattlesnake        102
2  1996  7/25/1996        UK      HB      10  Rattlesnake        103
3  1996  7/25/1996        UK      HB      10  Rattlesnake        104
4  1996  7/22/1996        UK      HB      11   El Radabob        111

  Surveyed_all_years  points  Cyanobacteria  Macroalgae  Octocoral  Others  \
0                  N     479            NaN      0.1587     0.0230     0.0
1                  N     525            NaN      0.2476     0.0400     0.0
2                  N     558            NaN      0.0323     0.0412     0.0
3                  N     446            NaN      0.4260     0.0493     0.0
4                  N     450            NaN      0.3156     0.0067     0.0

   Porifera  Seagrass  Stony_coral  Substrate  Unknown  Urchins  Zoanthidea
0    0.0125    0.0042          0.0     0.8017      NaN      0.0         0.0
1    0.0305    0.0000          0.0     0.6819      NaN      0.0         0.0
2    0.0394    0.0036          0.0     0.8835      NaN      0.0         0.0
3    0.0404    0.0000          0.0     0.4843      NaN      0.0         0.0
4    0.0000    0.3133          0.0     0.3644      NaN      0.0         0.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3918 entries, 0 to 3917
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                3918 non-null   int64
 1   Date                3912 non-null   object
 2   Subregion           3918 non-null   object
 3   Habitat             3918 non-null   object
 4   SiteID              3918 non-null   int64
 5   Site_name           3918 non-null   object
 6   StationID           3918 non-null   int64
 7   Surveyed_all_years  3918 non-null   object
 8   points              3918 non-null   int64
 9   Cyanobacteria       2171 non-null   float64
 10  Macroalgae          3918 non-null   float64
 11  Octocoral           3918 non-null   float64
 12  Others              3918 non-null   float64
 13  Porifera            3918 non-null   float64
 14  Seagrass            3918 non-null   float64
 15  Stony_coral         3918 non-null   float64
 16  Substrate           3918 non-null   float64
 17  Unknown             1766 non-null   float64
 18  Urchins             1747 non-null   float64
 19  Zoanthidea          3918 non-null   float64
dtypes: float64(11), int64(4), object(5)
memory usage: 612.3+ KB
None

--- Temperature Data ---
   OID_  SiteID    Site_name  Year  Month  Day  Time  TempC  TempF
0     1      10  Rattlesnake  2020      6   12  11.0  29.59  85.26
1     2      10  Rattlesnake  2020      6   12  12.0  29.76  85.57
2     3      10  Rattlesnake  2020      6   12  13.0  29.81  85.66
3     4      10  Rattlesnake  2020      6   12  14.0  30.19  86.34
4     5      10  Rattlesnake  2020      6   12  15.0  30.34  86.61
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5105020 entries, 0 to 5105019
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   OID_       int64
 1   SiteID     int64
 2   Site_name  object
 3   Year       int64
 4   Month      int64
 5   Day        int64
 6   Time       float64
 7   TempC      float64
 8   TempF      float64
dtypes: float64(3), int64(5), object(1)
memory usage: 350.5+ MB
None

--- Locations Data ---
   OID_ Region Site_Code  SiteID    Site_name Habitat Subregion  StationID  \
0    29  FKNMS       9H1      10  Rattlesnake      HB        UK        101
1    30  FKNMS       9H1      10  Rattlesnake      HB        UK        102
2    31  FKNMS       9H1      10  Rattlesnake      HB        UK        103
3    32  FKNMS       9H1      10  Rattlesnake      HB        UK        104
4    33  FKNMS       9H2      11   El Radabob      HB        UK        111

   First_Year_surveyed  length_m  Depth_ft    latDD    lonDD  latDeg  latMin  \
0                 1996        23         6  25.1736 -80.3475    25.0  10.416
1                 1996        22         6  25.1736 -80.3475    25.0  10.416
2                 1996        23         6  25.1736 -80.3475    25.0  10.416
3                 1996        25         6  25.1736 -80.3475    25.0  10.416
4                 1996        22         9  25.1201 -80.3782    25.0   7.206

   lonDeg  lonMin
0   -80.0  20.850
1   -80.0  20.850
2   -80.0  20.850
3   -80.0  20.850
4   -80.0  22.692
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OID_                 184 non-null    int64
 1   Region               184 non-null    object
 2   Site_Code            184 non-null    object
 3   SiteID               184 non-null    int64
 4   Site_name            184 non-null    object
 5   Habitat              184 non-null    object
 6   Subregion            184 non-null    object
 7   StationID            184 non-null    int64
 8   First_Year_surveyed  184 non-null    int64
 9   length_m             184 non-null    int64
 10  Depth_ft             184 non-null    int64
 11  latDD                184 non-null    float64
 12  lonDD                184 non-null    float64
 13  latDeg               184 non-null    float64
 14  latMin               184 non-null    float64
 15  lonDeg               184 non-null    float64
 16  lonMin               184 non-null    float64
dtypes: float64(6), int64(6), object(5)
memory usage: 24.6+ KB
None

![Data Processing Funnel](d_4.png)
## This block deals with missing values in the DataFrames. It first prints the number of missing values in each column. Then, it provides examples of handling missing values (dropping rows and filling with the mean).  Remember that the specific handling of missing values should be adapted based on the nature of your data and the analysis you intend to perform.

In [4]:
# Handle missing values

print("\n--- Missing Values Before Handling ---")
print("Stony Coral:\n", df_stony_coral.isnull().sum())
print("\nTaxa Groups:\n", df_taxa_groups.isnull().sum())
print("\nTemperature:\n", df_temperature.isnull().sum())
print("\nLocations:\n", df_locations.isnull().sum())

# Example: Drop rows with any missing values in stony coral data
df_stony_coral = df_stony_coral.dropna()

# Example: Fill missing temperature values with the mean
if 'Temperature' in df_temperature.columns:  # Check if 'Temperature' column exists
    df_temperature['Temperature'] = df_temperature['Temperature'].fillna(df_temperature['Temperature'].mean())

print("\n--- Missing Values After Handling ---")
print("Stony Coral:\n", df_stony_coral.isnull().sum())
print("Taxa Groups:\n", df_taxa_groups.isnull().sum())
print("Temperature:\n", df_temperature.isnull().sum())
print("Locations:\n", df_locations.isnull().sum())

--- Missing Values Before Handling ---
Stony Coral:
 OID_                                 0
Year                                 0
Date                                 6
Subregion                            0
Habitat                              0
SiteID                               0
Site_name                            0
StationID                            0
Surveyed_all_years                   0
points                               0
Acropora_cervicornis                 0
Acropora_palmata                     0
Agaricia_fragilis                    0
Agaricia_lamarcki                    0
Cladocora_arbuscula                  0
Colpophyllia_natans                  0
Dendrogyra_cylindrus                 0
Dichocoenia_stokesii                 0
Diploria_labyrinthiformis            0
Eusmilia_fastigiata                  0
Favia_fragum                         0
Helioseris_cucullata                 0
Isophyllia_rigida                    0
Isophyllia_sinuosa                   0
Madracis_aurentenra                  0
Madracis_decactis_complex            0
Manicina_areolata                    0
Meandrina_meandrites                 0
Millepora_alcicornis                 0
Millepora_complanata                 0
Montastraea_cavernosa                0
Mussa_angulosa                       0
Mycetophyllia_aliciae                0
Mycetophyllia_ferox                  0
Mycetophyllia_lamarckiana_complex    0
Oculina_diffusa                      0
Oculina_robusta                      0
Orbicella_annularis_complex          0
Phyllangia_americana                 0
Porites_astreoides                   0
Porites_porites_complex              0
Pseudodiploria_clivosa               0
Pseudodiploria_strigosa              0
Scleractinia                         0
Scolymia_sp                          0
Siderastrea_radians                  0
Siderastrea_siderea                  0
Solenastrea_bournoni                 0
Stephanocoenia_intersepta            0
Undaria_agaricites_complex           0
dtype: int64

Taxa Groups:
 Year                     0
Date                     6
Subregion                0
Habitat                  0
SiteID                   0
Site_name                0
StationID                0
Surveyed_all_years       0
points                   0
Cyanobacteria         1747
Macroalgae               0
Octocoral                0
Others                   0
Porifera                 0
Seagrass                 0
Stony_coral              0
Substrate                0
Unknown               2152
Urchins               2171
Zoanthidea               0
dtype: int64

Temperature:
 OID_         0
SiteID       0
Site_name    0
Year         0
Month        0
Day          0
Time         0
TempC        0
TempF        2
dtype: int64

Locations:
 OID_                   0
Region                 0
Site_Code              0
SiteID                 0
Site_name              0
Habitat                0
Subregion              0
StationID              0
First_Year_surveyed    0
length_m               0
Depth_ft               0
latDD                  0
lonDD                  0
latDeg                 0
latMin                 0
lonDeg                 0
lonMin                 0
dtype: int64

--- Missing Values After Handling ---
Stony Coral:
 OID_                                 0
Year                                 0
Date                                 0
Subregion                            0
Habitat                              0
SiteID                               0
Site_name                            0
StationID                            0
Surveyed_all_years                   0
points                               0
Acropora_cervicornis                 0
Acropora_palmata                     0
Agaricia_fragilis                    0
Agaricia_lamarcki                    0
Cladocora_arbuscula                  0
Colpophyllia_natans                  0
Dendrogyra_cylindrus                 0
Dichocoenia_stokesii                 0
Diploria_labyrinthiformis            0
Eusmilia_fastigiata                  0
Favia_fragum                         0
Helioseris_cucullata                 0
Isophyllia_rigida                    0
Isophyllia_sinuosa                   0
Madracis_aurentenra                  0
Madracis_decactis_complex            0
Manicina_areolata                    0
Meandrina_meandrites                 0
Millepora_alcicornis                 0
Millepora_complanata                 0
Montastraea_cavernosa                0
Mussa_angulosa                       0
Mycetophyllia_aliciae                0
Mycetophyllia_ferox                  0
Mycetophyllia_lamarckiana_complex    0
Oculina_diffusa                      0
Oculina_robusta                      0
Orbicella_annularis_complex          0
Phyllangia_americana                 0
Porites_astreoides                   0
Porites_porites_complex              0
Pseudodiploria_clivosa               0
Pseudodiploria_strigosa              0
Scleractinia                         0
Scolymia_sp                          0
Siderastrea_radians                  0
Siderastrea_siderea                  0
Solenastrea_bournoni                 0
Stephanocoenia_intersepta            0
Undaria_agaricites_complex           0
dtype: int64
Taxa Groups:
 Year                     0
Date                     6
Subregion                0
Habitat                  0
SiteID                   0
Site_name                0
StationID                0
Surveyed_all_years       0
points                   0
Cyanobacteria         1747
Macroalgae               0
Octocoral                0
Others                   0
Porifera                 0
Seagrass                 0
Stony_coral              0
Substrate                0
Unknown               2152
Urchins               2171
Zoanthidea               0
dtype: int64
Temperature:
 OID_         0
SiteID       0
Site_name    0
Year         0
Month        0
Day          0
Time         0
TempC        0
TempF        2
dtype: int64
Locations:
 OID_                   0
Region                 0
Site_Code              0
SiteID                 0
Site_name              0
Habitat                0
Subregion              0
StationID              0
First_Year_surveyed    0
length_m               0
Depth_ft               0
latDD                  0
lonDD                  0
latDeg                 0
latMin                 0
lonDeg                 0
lonMin                 0
dtype: int64

![Standardizing Column Name](d_5.png)
## This block standardizes column names across the DataFrames to ensure consistency. Consistent column names are essential for merging and comparing data.  The example code renames 'Site_name' to 'SiteName' and 'Year' to 'year', but you should adjust this based on your specific requirements.

In [5]:
# Standardize column names (example; adjust based on your needs)

print("\n--- Column Names Before Standardization ---")
print("Stony Coral:", df_stony_coral.columns)
print("\nTaxa Groups:", df_taxa_groups.columns)
print("\nTemperature:", df_temperature.columns)
print("\nLocations:", df_locations.columns)

if 'Site_name' in df_stony_coral.columns:
    df_stony_coral = df_stony_coral.rename(columns={'Site_name': 'SiteName'})
if 'Site_name' in df_taxa_groups.columns:
    df_taxa_groups = df_taxa_groups.rename(columns={'Site_name': 'SiteName'})
if 'Year' in df_temperature.columns:
    df_temperature = df_temperature.rename(columns={'Year': 'year'})
if 'Year' in df_stony_coral.columns:
    df_stony_coral = df_stony_coral.rename(columns={'Year': 'year'})
if 'Year' in df_taxa_groups.columns:
    df_taxa_groups = df_taxa_groups.rename(columns={'Year': 'year'})

print("\n--- Column Names After Standardization ---")
print("Stony Coral:", df_stony_coral.columns)
print("\nTaxa Groups:", df_taxa_groups.columns)
print("\nTemperature:", df_temperature.columns)
print("\nLocations:", df_locations.columns)

--- Column Names Before Standardization ---
Stony Coral: Index(['OID_', 'Year', 'Date', 'Subregion', 'Habitat', 'SiteID', 'Site_name',
       'StationID', 'Surveyed_all_years', 'points', 'Acropora_cervicornis',
       'Acropora_palmata', 'Agaricia_fragilis', 'Agaricia_lamarcki',
       'Cladocora_arbuscula', 'Colpophyllia_natans', 'Dendrogyra_cylindrus',
       'Dichocoenia_stokesii', 'Diploria_labyrinthiformis',
       'Eusmilia_fastigiata', 'Favia_fragum', 'Helioseris_cucullata',
       'Isophyllia_rigida', 'Isophyllia_sinuosa', 'Madracis_aurentenra',
       'Madracis_decactis_complex', 'Manicina_areolata',
       'Meandrina_meandrites', 'Millepora_alcicornis', 'Millepora_complanata',
       'Montastraea_cavernosa', 'Mussa_angulosa', 'Mycetophyllia_aliciae',
       'Mycetophyllia_ferox', 'Mycetophyllia_lamarckiana_complex',
       'Oculina_diffusa', 'Oculina_robusta', 'Orbicella_annularis_complex',
       'Phyllangia_americana', 'Porites_astreoides', 'Porites_porites_complex',
       'Pseudodiploria_clivosa', 'Pseudodiploria_strigosa', 'Scleractinia',
       'Scolymia_sp', 'Siderastrea_radians', 'Siderastrea_siderea',
       'Solenastrea_bournoni', 'Stephanocoenia_intersepta',
       'Undaria_agaricites_complex'],
      dtype='object')

Taxa Groups: Index(['Year', 'Date', 'Subregion', 'Habitat', 'SiteID', 'Site_name',
       'StationID', 'Surveyed_all_years', 'points', 'Cyanobacteria',
       'Macroalgae', 'Octocoral', 'Others', 'Porifera', 'Seagrass',
       'Stony_coral', 'Substrate', 'Unknown', 'Urchins', 'Zoanthidea'],
      dtype='object')

Temperature: Index(['OID_', 'SiteID', 'Site_name', 'Year', 'Month', 'Day', 'Time', 'TempC',
       'TempF'],
      dtype='object')

Locations: Index(['OID_', 'Region', 'Site_Code', 'SiteID', 'Site_name', 'Habitat',
       'Subregion', 'StationID', 'First_Year_surveyed', 'length_m', 'Depth_ft',
       'latDD', 'lonDD', 'latDeg', 'latMin', 'lonDeg', 'lonMin'],
      dtype='object')

--- Column Names After Standardization ---
Stony Coral: Index(['OID_', 'year', 'Date', 'Subregion', 'Habitat', 'SiteID', 'SiteName',
       'StationID', 'Surveyed_all_years', 'points', 'Acropora_cervicornis',
       'Acropora_palmata', 'Agaricia_fragilis', 'Agaricia_lamarcki',
       'Cladocora_arbuscula', 'Colpophyllia_natans', 'Dendrogyra_cylindrus',
       'Dichocoenia_stokesii', 'Diploria_labyrinthiformis',
       'Eusmilia_fastigiata', 'Favia_fragum', 'Helioseris_cucullata',
       'Isophyllia_rigida', 'Isophyllia_sinuosa', 'Madracis_aurentenra',
       'Madracis_decactis_complex', 'Manicina_areolata',
       'Meandrina_meandrites', 'Millepora_alcicornis', 'Millepora_complanata',
       'Montastraea_cavernosa', 'Mussa_angulosa', 'Mycetophyllia_aliciae',
       'Mycetophyllia_ferox', 'Mycetophyllia_lamarckiana_complex',
       'Oculina_diffusa', 'Oculina_robusta', 'Orbicella_annularis_complex',
       'Phyllangia_americana', 'Porites_astreoides', 'Porites_porites_complex',
       'Pseudodiploria_clivosa', 'Pseudodiploria_strigosa', 'Scleractinia',
       'Scolymia_sp', 'Siderastrea_radians', 'Siderastrea_siderea',
       'Solenastrea_bournoni', 'Stephanocoenia_intersepta',
       'Undaria_agaricites_complex'],
      dtype='object')

Taxa Groups: Index(['year', 'Date', 'Subregion', 'Habitat', 'SiteID', 'SiteName',
       'StationID', 'Surveyed_all_years', 'points', 'Cyanobacteria',
       'Macroalgae', 'Octocoral', 'Others', 'Porifera', 'Seagrass',
       'Stony_coral', 'Substrate', 'Unknown', 'Urchins', 'Zoanthidea'],
      dtype='object')

Temperature: Index(['OID_', 'SiteID', 'Site_name', 'year', 'Month', 'Day', 'Time', 'TempC',
       'TempF'],
      dtype='object')

Locations: Index(['OID_', 'Region', 'Site_Code', 'SiteID', 'Site_name', 'Habitat',
       'Subregion', 'StationID', 'First_Year_surveyed', 'length_m', 'Depth_ft',
       'latDD', 'lonDD', 'latDeg', 'latMin', 'lonDeg', 'lonMin'],
      dtype='object')

# Extract Year from Temperature Data
#
## This block extracts the year from the 'Date' or 'DateTime' column in the temperature data. This is often necessary for time-based analysis.  The code checks for both column names and uses pd.to_datetime() to convert the column to datetime objects before extracting the year.

In [6]:
# Extract year from temperature data (if applicable)

print("\n--- Temperature Data Before Year Extraction ---")
print(df_temperature.head())
print(df_temperature.dtypes)

if 'Date' in df_temperature.columns:  # Check if 'Date' column exists
    df_temperature['Year'] = pd.to_datetime(df_temperature['Date']).dt.year
elif 'DateTime' in df_temperature.columns: # Check if 'DateTime' column exists
    df_temperature['Year'] = pd.to_datetime(df_temperature['DateTime']).dt.year

print("\n--- Temperature Data After Year Extraction ---")
print(df_temperature.head())
print(df_temperature.dtypes)

--- Temperature Data Before Year Extraction ---
   OID_  SiteID    Site_name  year  Month  Day  Time  TempC  TempF
0     1      10  Rattlesnake  2020      6   12  11.0  29.59  85.26
1     2      10  Rattlesnake  2020      6   12  12.0  29.76  85.57
2     3      10  Rattlesnake  2020      6   12  13.0  29.81  85.66
3     4      10  Rattlesnake  2020      6   12  14.0  30.19  86.34
4     5      10  Rattlesnake  2020      6   12  15.0  30.34  86.61
OID_           int64
SiteID         int64
Site_name     object
year           int64
Month          int64
Day            int64
Time         float64
TempC        float64
TempF        float64
dtype: object

--- Temperature Data After Year Extraction ---
   OID_  SiteID    Site_name  year  Month  Day  Time  TempC  TempF
0     1      10  Rattlesnake  2020      6   12  11.0  29.59  85.26
1     2      10  Rattlesnake  2020      6   12  12.0  29.76  85.57
2     3      10  Rattlesnake  2020      6   12  13.0  29.81  85.66
3     4      10  Rattlesnake  2020      6   12  14.0  30.19  86.34
4     5      10  Rattlesnake  2020      6   12  15.0  30.34  86.61
OID_           int64
SiteID         int64
Site_name     object
year           int64
Month          int64
Day            int64
Time         float64
TempC        float64
TempF        float64
dtype: object

# Merge Location Data 
#
## This block demonstrates how to merge location data with the stony coral data using the 'SiteName' column.  Merging might be necessary if you want to include location attributes in your coral analysis.  The 'how' parameter in pd.merge() determines the type of join (left, right, inner, outer).

In [7]:
# Merge location data (optional; if you need to combine location information)

print("\n--- DataFrames Before Merge (Example) ---")
print("Stony Coral Columns:", df_stony_coral.columns)
print("\nLocations Columns:", df_locations.columns)

if 'SiteName' in df_stony_coral.columns and 'SiteName' in df_locations.columns:
    df_stony_coral = pd.merge(df_stony_coral, df_locations, on='SiteName', how='left')
    print("\n--- Stony Coral Data After Merge ---")
    print(df_stony_coral.head())
    print(df_stony_coral.info())

print("\n--- DataFrames After Optional Merge ---")
print("Stony Coral Columns:", df_stony_coral.columns)
print("\nTaxa Groups Columns:", df_taxa_groups.columns)
print("\nTemperature Columns:", df_temperature.columns)
print("\nLocations Columns:", df_locations.columns)

--- DataFrames Before Merge (Example) ---
Stony Coral Columns: Index(['OID_', 'year', 'Date', 'Subregion', 'Habitat', 'SiteID', 'SiteName',
       'StationID', 'Surveyed_all_years', 'points', 'Acropora_cervicornis',
       'Acropora_palmata', 'Agaricia_fragilis', 'Agaricia_lamarcki',
       'Cladocora_arbuscula', 'Colpophyllia_natans', 'Dendrogyra_cylindrus',
       'Dichocoenia_stokesii', 'Diploria_labyrinthiformis',
       'Eusmilia_fastigiata', 'Favia_fragum', 'Helioseris_cucullata',
       'Isophyllia_rigida', 'Isophyllia_sinuosa', 'Madracis_aurentenra',
       'Madracis_decactis_complex', 'Manicina_areolata',
       'Meandrina_meandrites', 'Millepora_alcicornis', 'Millepora_complanata',
       'Montastraea_cavernosa', 'Mussa_angulosa', 'Mycetophyllia_aliciae',
       'Mycetophyllia_ferox', 'Mycetophyllia_lamarckiana_complex',
       'Oculina_diffusa', 'Oculina_robusta', 'Orbicella_annularis_complex',
       'Phyllangia_americana', 'Porites_astreoides', 'Porites_porites_complex',
       'Pseudodiploria_clivosa', 'Pseudodiploria_strigosa', 'Scleractinia',
       'Scolymia_sp', 'Siderastrea_radians', 'Siderastrea_siderea',
       'Solenastrea_bournoni', 'Stephanocoenia_intersepta',
       'Undaria_agaricites_complex'],
      dtype='object')

Locations Columns: Index(['OID_', 'Region', 'Site_Code', 'SiteID', 'Site_name', 'Habitat',
       'Subregion', 'StationID', 'First_Year_surveyed', 'length_m', 'Depth_ft',
       'latDD', 'lonDD', 'latDeg', 'latMin', 'lonDeg', 'lonMin'],
      dtype='object')

--- DataFrames After Optional Merge ---
Stony Coral Columns: Index(['OID_', 'year', 'Date', 'Subregion', 'Habitat', 'SiteID', 'SiteName',
       'StationID', 'Surveyed_all_years', 'points', 'Acropora_cervicornis',
       'Acropora_palmata', 'Agaricia_fragilis', 'Agaricia_lamarcki',
       'Cladocora_arbuscula', 'Colpophyllia_natans', 'Dendrogyra_cylindrus',
       'Dichocoenia_stokesii', 'Diploria_labyrinthiformis',
       'Eusmilia_fastigiata', 'Favia_fragum', 'Helioseris_cucullata',
       'Isophyllia_rigida', 'Isophyllia_sinuosa', 'Madracis_aurentenra',
       'Madracis_decactis_complex', 'Manicina_areolata',
       'Meandrina_meandrites', 'Millepora_alcicornis', 'Millepora_complanata',
       'Montastraea_cavernosa', 'Mussa_angulosa', 'Mycetophyllia_aliciae',
       'Mycetophyllia_ferox', 'Mycetophyllia_lamarckiana_complex',
       'Oculina_diffusa', 'Oculina_robusta', 'Orbicella_annularis_complex',
       'Phyllangia_americana', 'Porites_astreoides', 'Porites_porites_complex',
       'Pseudodiploria_clivosa', 'Pseudodiploria_strigosa', 'Scleractinia',
       'Scolymia_sp', 'Siderastrea_radians', 'Siderastrea_siderea',
       'Solenastrea_bournoni', 'Stephanocoenia_intersepta',
       'Undaria_agaricites_complex'],
      dtype='object')

Taxa Groups Columns: Index(['year', 'Date', 'Subregion', 'Habitat', 'SiteID', 'SiteName',
       'StationID', 'Surveyed_all_years', 'points', 'Cyanobacteria',
       'Macroalgae', 'Octocoral', 'Others', 'Porifera', 'Seagrass',
       'Stony_coral', 'Substrate', 'Unknown', 'Urchins', 'Zoanthidea'],
      dtype='object')

Temperature Columns: Index(['OID_', 'SiteID', 'Site_name', 'year', 'Month', 'Day', 'Time', 'TempC',
       'TempF'],
      dtype='object')

Locations Columns: Index(['OID_', 'Region', 'Site_Code', 'SiteID', 'Site_name', 'Habitat',
       'Subregion', 'StationID', 'First_Year_surveyed', 'length_m', 'Depth_ft',
       'latDD', 'lonDD', 'latDeg', 'latMin', 'lonDeg', 'lonMin'],
      dtype='object')

# Save Processed Data 
#
##  This block shows examples of how to save the processed DataFrames to CSV or Parquet files. Saving the processed data is useful if you plan to use it in other notebooks, as it avoids having to repeat the preprocessing steps. The code is commented out; uncomment the lines if you want to save the data.

In [10]:
# Save processed data 

# Define the output directory
output_dir = "C:\\temp"  # Or your desired output directory (e.g., "C:/temp")

# --- Robust Data Saving ---

# 1. Ensure Output Directory Exists
import os
os.makedirs(output_dir, exist_ok=True)  # Create directory if it doesn't exist

# 2. Rebuild DataFrames from Values (Strongest Method)
def rebuild_dataframe(df):
    """Rebuilds a Pandas DataFrame to ensure a clean structure."""
    new_df = pd.DataFrame(df.values, columns=df.columns)
    return new_df.reset_index(drop=True)

df_stony_coral = rebuild_dataframe(df_stony_coral)
df_taxa_groups = rebuild_dataframe(df_taxa_groups)
df_temperature = rebuild_dataframe(df_temperature)
df_locations = rebuild_dataframe(df_locations)

# 3. Handle Mixed Data Types (Convert to String if Necessary)
def handle_mixed_types(df):
    """Converts columns to numeric where possible, else to string."""
    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col])
        except ValueError:
            df[col] = df[col].astype(str)
    return df

df_stony_coral = handle_mixed_types(df_stony_coral)
df_taxa_groups = handle_mixed_types(df_taxa_groups)
df_temperature = handle_mixed_types(df_temperature)
df_locations = handle_mixed_types(df_locations)

# 4. Save to CSV (Most Reliable Format)
def save_to_csv(df, filename):
    """Saves a DataFrame to CSV in the output directory."""
    filepath = os.path.join(output_dir, filename)
    df.to_csv(filepath, index=False, encoding='utf-8')  # Explicit encoding
    print(f"Saved to: {filepath}")

save_to_csv(df_stony_coral, "processed_stony_coral.csv")
save_to_csv(df_taxa_groups, "processed_taxa_groups.csv")
save_to_csv(df_temperature, "processed_temperature.csv")
save_to_csv(df_locations, "processed_locations.csv")

# Example: Save to Parquet (Optional, if needed for large files)
# def save_to_parquet(df, filename):
#     """Saves a DataFrame to Parquet in the output directory."""
#     filepath = os.path.join(output_dir, filename)
#     df.to_parquet(filepath, index=False)
#     print(f"Saved to: {filepath}")

# save_to_parquet(df_stony_coral, "processed_stony_coral.parquet")
# save_to_parquet(df_taxa_groups, "processed_taxa_groups.parquet")
# save_to_parquet(df_temperature, "processed_temperature.parquet")
# save_to_parquet(df_locations, "processed_locations.parquet")

print("\n--- Data Saving Complete ---")
print(f"Processed data saved to: {output_dir}")

Saved to: C:\temp\processed_stony_coral.csv
Saved to: C:\temp\processed_taxa_groups.csv
Saved to: C:\temp\processed_temperature.csv
Saved to: C:\temp\processed_locations.csv

--- Data Saving Complete ---
Processed data saved to: C:\temp